version: "3.9"
services:
  chestxray-model:
    image: xray-model:v1
  gateway:
    image: xray-gateway:001
    environment:
      - TF_SERVING_HOST=chestxray-model:8500
    ports:
      - "9696:9696"